from __future__ import annotations

from pathlib import Path

TRUE_VALUES = {"1", "true", "yes", "y", "on"}
FALSE_VALUES = {"0", "false", "no", "n", "off"}


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key] = value
    return values


def write_env_file(path: Path, values: dict[str, str], header: str = "") -> None:
    lines: list[str] = []
    if header:
        lines.append(header.rstrip())
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def is_stage(values: dict[str, str]) -> bool:
    raw = values.get("STAGE", "OFF").strip().lower()
    if raw in TRUE_VALUES:
        return True
    if raw in FALSE_VALUES:
        return False
    raise ValueError("STAGE должен быть ON или OFF")


def _value(values: dict[str, str], key: str, default: str) -> str:
    value = values.get(key, "").strip()
    return value if value else default


def _int_value(values: dict[str, str], key: str, default: int) -> int:
    raw = _value(values, key, str(default))
    try:
        parsed = int(raw)
    except ValueError as exc:
        raise ValueError(f"{key} должен быть целым числом, сейчас: {raw!r}") from exc
    if parsed <= 0:
        raise ValueError(f"{key} должен быть больше 0, сейчас: {parsed}")
    return parsed


def build_runtime_env(base: dict[str, str]) -> dict[str, str]:
    stage = is_stage(base)
    env_name = "stage" if stage else "prod"
    prefix = "STAGE" if stage else "PROD"
    domain = _value(base, f"{prefix}_DOMAIN", "beta.twaps.ru" if stage else "twaps.ru")
    protocol = _value(base, "PUBLIC_PROTOCOL", "https")
    ws_protocol = "wss" if protocol == "https" else "ws"

    compose_project_name = _value(
        base,
        f"{prefix}_COMPOSE_PROJECT_NAME",
        _value(base, "COMPOSE_PROJECT_NAME", f"twap_{env_name}"),
    )

    return {
        "APP_ENV": env_name,
        "COMPOSE_PROJECT_NAME": compose_project_name,
        "PUBLIC_DOMAIN": domain,
        "PUBLIC_BASE_URL": f"{protocol}://{domain}",
        "PUBLIC_SIGNAL_WS_URL": f"{ws_protocol}://{domain}/ws/signals",
        "LOCAL_UI_PORT": str(_int_value(base, f"{prefix}_LOCAL_UI_PORT", 18080 if stage else 8080)),
        "SIGNAL_SERVER_PORT": str(_int_value(base, f"{prefix}_SIGNAL_SERVER_PORT", 18090 if stage else 8090)),
        "PHPMYADMIN_PORT": str(_int_value(base, f"{prefix}_PHPMYADMIN_PORT", 18081 if stage else 8081)),
        "MYSQL_HOST_PORT": str(_int_value(base, f"{prefix}_MYSQL_HOST_PORT", 13306 if stage else 3306)),
    }


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def generate_env_files(root: Path | None = None) -> dict[str, str]:
    root = root or project_root()
    base = read_env_file(root / ".env")
    runtime = build_runtime_env(base)
    write_env_file(
        root / ".env.runtime",
        runtime,
        "# Generated by tools/env_profile.py. Do not edit manually.",
    )
    merged = dict(base)
    merged.update(runtime)
    write_env_file(
        root / ".env.compose.generated",
        merged,
        "# Generated by tools/env_profile.py. Contains .env values + derived runtime values.",
    )
    return runtime


if __name__ == "__main__":
    runtime_values = generate_env_files()
    for item in [
        "APP_ENV",
        "PUBLIC_DOMAIN",
        "LOCAL_UI_PORT",
        "SIGNAL_SERVER_PORT",
        "PHPMYADMIN_PORT",
        "MYSQL_HOST_PORT",
    ]:
        print(f"{item}={runtime_values[item]}")
